Repository netlify/build-image, pull requests merged in 2020-11, with the labels that each got.

#474 Support installing tools via Homebrew (take 2)
  Dockerfile
  included_software.md
  run-build-functions.sh
Labels: type: feature

#487 Improve release docs
  CONTRIBUTING.md
Labels: type: chore

#489 Fix homebrew default bundle file
  run-build-functions.sh
Labels: type: feature

#490 Improve `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: type: chore

#491 Remove default Swift version
  Dockerfile
  run-build-functions.sh
  run-build.sh
Labels: hack-week-2020, type: chore

#495 Update Swift docs in included_software.md
  included_software.md
Labels: type: chore
