Repository netlify/build-image, pull requests merged in 2020-12, with the labels that each got.

#497 Document support for Zola
  included_software.md
Labels: type: chore

#502 Pin homebrew install to a specific commit
  Dockerfile
Labels: type: bug

#477 Add Rust support
  Dockerfile
  included_software.md
  run-build-functions.sh
  run-build.sh
Labels: needs docs, type: feature
