Repository netlify/build-image, pull requests merged in 2020-06, with the labels that each got.

#363 Add support for PYTHON_VERSION env variable.
  run-build-functions.sh
  run-build.sh
  test-tools/start-image.sh
  test-tools/test-build.sh
Labels: type: feature

#421 Upgrade preinstalled Go version to 1.14.4
  Dockerfile
  run-build.sh
Labels: type: chore

#420 Upgrade preinstalled Ruby version to 2.7.1
  Dockerfile
  run-build.sh
Labels: type: chore

#410 Add Intl for PHP
  Dockerfile
Labels: enhancement

#442 Add line of documentation about `CONTRIBUTING.md`
  README.md
Labels: type: chore
