Repository netlify/build-image, pull requests merged in 2020-05, with the labels that each got.

#407 Default to xenial tag for testing
  test-tools/start-image.sh
  test-tools/test-build.sh
Labels: type: bug

#409 Tag xenial builds as latest
  Jenkinsfile
Labels: type: chore

#411 Support installing tools via homebrew
  Dockerfile
  included_software.md
  run-build-functions.sh
Labels: type: feature

#414 Revert "Support installing tools via homebrew"
  Dockerfile
  included_software.md
  run-build-functions.sh
Labels: type: chore

#417 Do not run `yarn` if `package.json` has not changed
  run-build-functions.sh
Labels: feat/builds, type: feature

#413 Remove NETLIFY_BUILD_NODE_VERSION & special handling of its nvm dir
  Dockerfile
  run-build-functions.sh
Labels: type: chore

#419 Fix xenial latest tag
  Jenkinsfile
Labels: type: chore

#425 Fix `nvm` caching
  run-build-functions.sh
Labels: type: bug

#418 Move NF-build node to later image and lock node 10 version.
  Dockerfile
Labels: type: feature

#424 Cache `.netlify/plugins/` directory
  run-build-functions.sh
Labels: feat/builds, type: feature

#427 Revert "Yarn speed improvements PR"
  run-build-functions.sh
Labels: bug

#428 `3.3.13` release
  CHANGELOG.md
  package.json
Labels: type: bug

#429 Fix `.netlify/plugins` caching
  run-build-functions.sh
Labels: type: bug
