Repository netlify/build-image, pull requests merged in 2021-11, with the labels that each got.

#678 chore(docs): change the CI references in our contributing docs and add missing sections
  CONTRIBUTING.md
Labels: type: chore

#680 chore: Add additional Go version info for Xenial
  included_software.md
Labels: docs, type: chore

#682 fix(yarn): add the default installed yarn binary to PATH
  Dockerfile
  tests/node/yarn.bats
Labels: type: bug

#683 fix(yarn): add the default installed yarn binary to PATH (xenial)
  Dockerfile
  tests/node/yarn.bats
Labels: type: bug

#686 feat: add libvips
  Dockerfile
  included_software.md
  tests/vips/base.bats
Labels: type: bug

#689 chore(contributing): update the contributing docs with the renovate auto update info
  CONTRIBUTING.md
Labels: type: chore, automerge

#690 chore(ci): completely drop Jenkins
  Jenkinsfile
Labels: type: chore, automerge

#691 chore(ci): completely drop Jenkins - xenial
  Jenkinsfile
Labels: type: chore, automerge

#692 chore(kodiak): add kodiak config - xenial
  .kodiak.toml
Labels: type: chore
