Repository netlify/build-image, pull requests merged in 2021-10, with the labels that each got.

#641 docs: Fix documented Xenial software versions
  included_software.md
Labels: type: bug, automerge

#637 docs: Specify minimum Ruby version supported on Focal
  included_software.md
Labels: type: chore, proj/focal-build-image, automerge

#642 fix: multiple yarn flags
  run-build-functions.sh
  tests/node/yarn.bats
Labels: type: bug

#644 fix: multiple yarn flags xenial
  run-build-functions.sh
  tests/node/yarn.bats
Labels: type: bug
