Repository netlify/build-image, pull requests merged in 2021-03, with the labels that each got.

#526 feat: better cache support for JS workspaces
  run-build-functions.sh
Labels: init/js-dependency-management, theme/monorepos, type: feature

#529 fix: changelog and pacakge.json versioning
  CHANGELOG.md
  package.json
Labels: type: chore

#530 chore: add release please
  .github/workflows/release-please.yml
  CONTRIBUTING.md
  package.json
Labels: type: chore

#532 fix(release-please): set the correct branch name
  .github/workflows/release-please.yml
Labels: type: bug

#534 chore(ci): add @erezrokah wonderful PR labeler
  .github/workflows/labeler.yml
Labels: type: chore

#475 Remove lingering processes logic
  run-build-functions.sh
Labels: proj/lingering-processes, type: chore

#538 fix: punctuation
  package.json
Labels: type: bug
