Repository netlify/build-image, pull requests merged in 2021-01, with the labels that each got.

#516 Add change in Docker image size to PRs
  .github/workflows/ci.yml
Labels: type: chore

#515 add webp to lfs config
  buildbot-git-config
Labels: type: feature

#521 Fix Rust caching issues
  run-build-functions.sh
Labels: type: bug
