Repository netlify/build-image, pull requests merged in 2021-04, with the labels that each got.

#542 chore(release-please): use GitHub app token
  .github/workflows/release-please.yml
Labels: type: chore

#543 feat: upgrade to Ubuntu 20.04 Focal Fossa
  Dockerfile
  Jenkinsfile
  README.md
  included_software.md
  run-build.sh
Labels: type: feature

#548 chore: update focal in ci and release-please scripts
  .github/workflows/ci.yml
  .github/workflows/release-please.yml
  test-tools/start-image.sh
  test-tools/test-build.sh
Labels: type: chore

#550 fix: Update homebrew install (#547)
  Dockerfile
Labels: type: bug

#552 chore: default php version to 7.4 in Focal
  run-build-functions.sh
  run-build.sh
Labels: type: chore

#551 chore: default php version to 5.6 in xenial
  run-build-functions.sh
  run-build.sh
Labels: type: chore

#557 Fix: release php default update for focal
  .github/workflows/release-please.yml
Labels: proj/new-build-image, type: bug, type: chore
