Repository netlify/build-image, pull requests merged in 2022-01, with the labels that each got.

#723 chore: add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: type: chore, automerge

#724 chore: update codeowners
  .github/CODEOWNERS
Labels: type: chore, automerge

#725 chore: warn when NODE_ENV == "production"
  run-build-functions.sh
Labels: type: chore

#733 chore: update release instructions
  CONTRIBUTING.md
Labels: type: chore

#736 fix: ci xenial
  Dockerfile
Labels: xenial, type: chore, type: bug

#734 chore: update release instructions
  CONTRIBUTING.md
Labels: type: chore

#726 chore: update codeowners
  .github/CODEOWNERS
Labels: type: chore, automerge
