Repository netlify/build-image, pull requests merged in 2022-11, with the labels that each got.

#867 chore: fix container structure tests
  focal.yaml
Labels: type: chore, automerge

#868 chore(xenial): fix container structure tests
  xenial.yaml
Labels: type: chore, automerge

#853 chore: add job to trigger intergation tests in buildbot
  .circleci/config.yml
  Dockerfile
Labels: type: chore

#869 chore: Remove Xenial references in the repo
  CONTRIBUTING.md
  README.md
Labels: type: chore, automerge

#858 feat: package manager detection for mono repositories
  Dockerfile
  README.md
  package-lock.json
  package.json
  run-build-functions.sh
  run-build.sh
  test-tools/start-image.sh
  test-tools/test-build.sh
  tests/get-build-info.mjs
Labels: type: feature

#872 fix: indentation issues in bash script
  run-build-functions.sh
Labels: type: bug

#870 fix: Bump Go to 1.19
  Dockerfile
  included_software.md
  run-build.sh
  tests/go/base.bats
Labels: type: bug, automerge
