Repository netlify/build-image, pull requests merged in 2022-06, with the labels that each got.

#713 fix: Bump Go to 1.17 and omit patch version
  Dockerfile
  included_software.md
  run-build-functions.sh
  run-build.sh
  tests/go/base.bats
Labels: type: chore, type: bug

#754 chore: use TARGETARCH arg in Dockerfile
  Dockerfile
Labels: type: chore

#790 Copy the ruby version into rvm/gems
  run-build-functions.sh
Labels: type: bug

#800 feat: add zstd compression algorithm to build image
  Dockerfile
Labels: type: feature

#803 feat: add zstd compression algorithm to build image
  .circleci/config.yml
  Dockerfile
Labels: type: feature, automerge
