Repository netlify/build-image, pull requests merged in 2022-09, with the labels that each got.

#828 chore: build image for multiple CPU architectures linux/amd64,linux/arm64
  .circleci/config.yml
  .editorconfig
  .github/workflows/whalescale.yml
  CONTRIBUTING.md
  Dockerfile
  Makefile
  focal-amd64.yaml
  focal.yaml
  run-build-functions.sh
  tests/go/base.bats
Labels: type: chore

#837 fix: update test to reflect new homebrew version
  focal-amd64.yaml
Labels: type: chore, type: bug, automerge

#836 feat: add Deno to focal
  Dockerfile
  focal-amd64.yaml
  focal.yaml
Labels: type: feature

#840 chore: smol copy improvement
  CONTRIBUTING.md
Labels: type: chore

#829 feat: update nvm and yarn to latest version
  Dockerfile
  focal.yaml
  included_software.md
  run-build.sh
  tests/node/yarn.bats
Labels: type: feature
