Repository netlify/build-image, pull requests merged in 2022-07, with the labels that each got.

#806 Revert "Copy the ruby version into rvm/gems"
  run-build-functions.sh
Labels: type: bug

#809 docs: update CONTRIBUTING.md with documentation about container structure tests
  CONTRIBUTING.md
Labels: type: chore, automerge

#817 tests: add additional structure tests
  focal.yaml
Labels: type: chore

#818 chore: make build-image arm64 compatible
  .circleci/config.yml
  .github/workflows/whalescale.yml
  Dockerfile
  focal.yaml
Labels: type: chore, automerge

#814 feat: add musl libc and its tools to build image
  Dockerfile
  focal.yaml
Labels: type: feature

#824 feat: add musl libc and its tools to build image
  Dockerfile
Labels: type: feature

#808 fix: cache ruby version gems dir
  run-build-functions.sh
Labels: type: bug

#813 chore: Fix tiny issues in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: type: chore, automerge
