Repository netlify/build-image, pull requests merged in 2022-03, with the labels that each got.

#755 chore: remove graphicsmagick apt-repo
  Dockerfile
Labels: type: chore

#752 feat: Support npm workspaces caching
  run-build-functions.sh
Labels: type: feature

#753 feat: Support npm workspaces caching
  run-build-functions.sh
Labels: type: feature

#761 fix: `pyenv` should use HTTPS to git clone
  Dockerfile
Labels: type: bug

#744 chore(ci): use stronger machines (#743)
  .circleci/config.yml
Labels: type: chore

#757 chore: remove code duplication in custom Node.js version logic
  run-build-functions.sh
Labels: type: chore, automerge

#758 chore: remove code duplication in custom Node.js version logic (Xenial)
  run-build-functions.sh
Labels: type: chore, automerge

#769 feat: replace `EXPERIMENTAL_NPM_WORKSPACES_CACHING` with a LaunchDarkly feature flag
  run-build-functions.sh
Labels: type: feature, automerge

#770 feat: replace `EXPERIMENTAL_NPM_WORKSPACES_CACHING` with a LaunchDarkly feature flag
  run-build-functions.sh
Labels: type: feature, automerge
