Repository netlify/build-image, pull requests merged in 2022-10, with the labels that each got.

#845 feat: add pnpm to build image
  .gitignore
  Dockerfile
  Makefile
  focal.yaml
  run-build-functions.sh
  run-build.sh
  test-tools/start-image.sh
  test-tools/test-build.sh
  tests/node/base.bats
  tests/node/pnpm.bats
  tests/node/yarn.bats
Labels: type: feature

#846 fix: incorporate breaking change in install_dependencies order
  run-build-functions.sh
  run-build.sh
  test-tools/test-build.sh
  xenial.yaml
Labels: type: bug

#856 feat: add the possiblity to add flags to the pnpm install command
  run-build-functions.sh
Labels: type: feature

#848 fix: Install Hugo extended by default
  Dockerfile
  focal-amd64.yaml
  included_software.md
Labels: type: bug

#854 chore: run pre & post install scripts
  run-build-functions.sh
  tests/node/bypass_cache.bats
Labels: type: chore

#860 fix: feature flag node corepack usage
  run-build-functions.sh
Labels: type: bug
