Repository netlify/build-image, pull requests merged in 2023-01, with the labels that each got.

#890 fix: ensure that .netlify is a directory and not a file or broken symlink
  run-build-functions.sh
Labels: type: bug

#892 chore: fix links in PR template
  .github/pull_request_template.md
Labels: type: chore, type: bug, automerge

#893 fix: corepack cannot be cached
  run-build-functions.sh
Labels: type: bug

#891 chore: fix capitalization and spelling of languages and package managers
  CONTRIBUTING.md
  Dockerfile
  focal.yaml
  included_software.md
  run-build-functions.sh
  tests/node/bypass_cache.bats
  tests/node/pnpm.bats
  tests/node/yarn.bats
Labels: type: chore, automerge

#900 fix(npm): allow multiple NPM_FLAGS during new install execution
  run-build-functions.sh
  tests/node/bypass_cache.bats
Labels: type: bug
